name: Compile MEX

on:
  # Trigger the workflow on push or pull request
  #push:
  pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 0 * * *'
  # Trigger the workflow manually
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

# Show the git ref in the workflow name if it is invoked manually.
run-name: ${{ github.event_name == 'workflow_dispatch' && format('Manual run {0}', inputs.git-ref) || '' }}

env:
  MATLAB_VERSION: R2023b
  MATLAB: /Applications/MATLAB_R2023b.app/bin/matlab

jobs:

  mex:
    name: Compile MEX
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12, macos-13, ubuntu-20.04, ubuntu-22.04]
        matlab: [R2020b, R2021a, R2021b, R2022a, R2022b, R2023a, R2023b, R2024a]

        include:
          # Only R2021a/b and R2022a are available on Windows 2019.
          - os: windows-2019
            matlab: R2021a
          - os: windows-2019
            matlab: R2021b
          - os: windows-2019
            matlab: R2022a

          # Below R2022a, MEX does not work on windows-latest due to the version of MS Visual Studio;
          # R2022a/b should work according to the documentation of MathWorks and GitHub Actions, but
          # they do not as of April 2024
          - os: windows-2022
            matlab: R2023a
          - os: windows-2022
            matlab: R2023b
          - os: windows-2022
            matlab: R2024a


    steps:

      - name: Set http.postBuffer and core.compression
        # This is a workaround for random "early EOF" of checkout.
        # See https://github.com/actions/checkout/issues/748, https://github.com/actions/checkout/issues/1379
        if: startsWith(matrix.os, 'windows')
        run: git config --global http.postBuffer 1048576000 && git config --global core.compression 0

      - name: Clone Repository (Latest)
        uses: actions/checkout@v4
        if: github.event.inputs.git-ref == ''
        with:
          submodules: recursive
        #   ssh-key: ${{ secrets.SSH_PRIVATE_KEY_ACT }} # This forces checkout to use SSH, not HTTPS
        # As of 231227, checkout with ssh fails frequently on Windows runners.
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v4
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
          submodules: recursive
        #   ssh-key: ${{ secrets.SSH_PRIVATE_KEY_ACT }} # This forces checkout to use SSH, not HTTPS
        # As of 231227, checkout with ssh fails frequently on Windows runners.

      - name: Miscellaneous setup
        run: bash .github/scripts/misc_setup

      - name: Link gfortran for MATLAB on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          GFVER=${{ env.GFORTRAN_VERSION }}
          if [[ "${{ matrix.os }}" = "ubuntu-20.04" ]] ; then
              GFVER=11
          fi
          if [[ "${{ matrix.matlab }}" = "R2020b" || "${{ matrix.matlab }}" = "R2021a" || "${{ matrix.matlab }}" = "R2021b" ]] ; then
              GFVER=9
          fi
          bash .github/scripts/link_gfortran "$GFVER"

      - name: Install Intel oneAPI on macOS
        if: startsWith(matrix.os, 'macos')
        run: bash .github/scripts/install_oneapi_macos.sh

      - name: Install Intel oneAPI on Windows
        if: startsWith(matrix.os, 'windows')
        #run: cmd.exe "/K" '".github\scripts\install_oneapi_windows.bat"'  # As of MATLAB R2023a, oneAPI 2024 does not work. Try again later.
        run: cmd.exe "/K" '".github\scripts\install_oneapi_windows.bat 2023"'

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.1.2
        with:
          release: ${{ matrix.matlab }}
          cache: true
          products: Parallel_Computing_Toolbox

      - name: Compile the MEX functions
        uses: matlab-actions/run-command@v2.1.1
        with:
          command: |
            options.debug = true;
            options.single = true;
            options.quadruple = true;
            options.classical = false;
            options.verbose = true;
            setup(options);
            testprima;
            cd matlab/examples;
            rosenbrock_example;

      - name: Store artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: prima-${{ matrix.os }}-${{ matrix.matlab }}
          path: |
            ./*
            !./benchmark
            !./.*
            !./*.log
            !./*.dot
            !./*.json


  mex_mac_silicon:
    name: Compile MEX, macOS ARM64
    runs-on: [self-hosted, macOS, ARM64]
    strategy:
      fail-fast: false

    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v4
        if: github.event.inputs.git-ref == ''
        with:
          submodules: recursive
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v4
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
          submodules: recursive

      - name: Miscellaneous setup
        run: bash .github/scripts/misc_setup

      - name: Conduct the test  # We do not use matlab-actions/run-command, which is not supported on macOS ARM64 as of 20240119
        run: ${{ env.MATLAB }} -nojvm -batch "options.debug = true; options.half = true; options.single = true; options.quadruple = true; options.classical = false; options.verbose = true; setup(options); testprima; cd matlab/examples; rosenbrock_example;"

      - name: Store artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: prima-macos-arm64-${{ env.MATLAB_VERSION }}
          path: |
            ./*
            !./benchmark
            !./.*
            !./*.log
            !./*.dot
            !./*.json
