name: Stress test on large problems, MATLAB

on:
  # Trigger the workflow on push or pull request
  #push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 6 1-31/2 * *'
  # Trigger the workflow manually
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
      random-seed:
        description: Random Seed (Optional)
        required: false
      precision:
        description: Test Precision (Optional)
        required: false

# Show the git ref in the workflow name if it is invoked manually.
run-name: ${{ github.event_name == 'workflow_dispatch' && format('Manual run {0} , seed {1}, precision {2}', inputs.git-ref, inputs.random-seed, inputs.precision) || '' }}

jobs:
  test:
    name: Stress test of PRIMA on large problems
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false

      # The matrix is the same as that of recursive_test_matlab.yml, except for `test`.
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, windows-2019, windows-latest, macos-11, macos-12, macos-13]
        matlab: [R2020b, R2021a, R2022a, R2023a, latest]
        solver: [uobyqa, newuoa, bobyqa, lincoa, cobyla]
        test: [normal, tough]

        # Exclude some versions of OS and MATLAB. We test ONLY the earliest and latest versions of MATLAB on each OS.
        exclude:
          # ubuntu-latest: test R2020b and latest
          - os: ubuntu-latest
            matlab: R2021a
          - os: ubuntu-latest
            matlab: R2022a
          - os: ubuntu-latest
            matlab: R2023a

          # ubuntu-20.04: test R2020b and latest
          - os: ubuntu-20.04
            matlab: R2021a
          - os: ubuntu-20.04
            matlab: R2022a
          - os: ubuntu-20.04
            matlab: R2023a

          # macos-13: test R2020b and latest
          - os: macos-13
            matlab: R2021a
          - os: macos-13
            matlab: R2022a
          - os: macos-13
            matlab: R2023a

          # macos-12: test R2022a and latest
          - os: macos-12
            matlab: R2020b
          - os: macos-12
            matlab: R2021a
          - os: macos-12
            matlab: R2023a

          # macos-11: test R2022a and latest
          - os: macos-11
            matlab: R2020b
          - os: macos-11
            matlab: R2021a
          - os: macos-11
            matlab: R2023a

          # windows-latest: test R2023a and latest
          - os: windows-latest
            matlab: R2020b
          - os: windows-latest
            matlab: R2021a
          - os: windows-latest
            matlab: R2022a

          # windows-2019: test R2021a and R2022a
          - os: windows-2019
            matlab: R2020b
          - os: windows-2019
            matlab: R2023a
          - os: windows-2019
            matlab: latest


    steps:

      - name: Set http.postBuffer and core.compression
        # This is a workaround for random "early EOF" of checkout.
        # See https://github.com/actions/checkout/issues/748, https://github.com/actions/checkout/issues/1379
        if: startsWith(matrix.os, 'windows')
        run: git config --global http.postBuffer 1048576000 && git config --global core.compression 0

      - name: Clone Repository (Latest)
        uses: actions/checkout@v4
        if: github.event.inputs.git-ref == ''
        with:
        #   ssh-key: ${{ secrets.SSH_PRIVATE_KEY_ACT }} # This forces checkout to use SSH, not HTTPS
        # As of 231227, checkout with ssh fails frequently on Windows runners.
          submodules: recursive
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v4
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
        #   ssh-key: ${{ secrets.SSH_PRIVATE_KEY_ACT }} # This forces checkout to use SSH, not HTTPS
        # As of 231227, checkout with ssh fails frequently on Windows runners.
          submodules: recursive

      - name: Miscellaneous setup
        run: bash .github/scripts/misc_setup

